services:
  nginx:
    container_name: nginx_inception
    depends_on:
      - wordpress
    build: requirements/nginx/.
    env_file:
      - .env
      - ../secrets/credentials
    volumes:
      - wp_volume:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    restart: on-failure
  
  wordpress:
    container_name: wp_inception
    depends_on:
      - mariadb
    build: requirements/wordpress/.
    env_file: 
      - .env
      - ../secrets/db_password.txt
      - ../secrets/credentials
    volumes:
      - wp_volume:/var/www/html
    networks:
      - inception
    restart: on-failure

  mariadb:
    container_name: mdb_inception
    build: requirements/mariadb/.
    env_file: 
      - .env
      - ../secrets/db_password.txt
      - ../secrets/db_root_password.txt
      - ../secrets/credentials
    volumes:
      - mdb_volume:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

volumes:
  wp_volume:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
  mdb_volume:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge
