#-------------------------------------#
# Purpose:

  # Designed to simplify the use of multiple application like :
  # Nginx
  # Wordpress: website
  # MariaDB: for database

  # Service steps:
    # 1st: depends_on - check dependencies before building the container
    # 2nd: build - launch each service in separate containers
    # 3rd: environment (not hard-coded in the file) - setting environment variables of the container (API keys, passwords, database credentials securely)
    # 4th: volumes - specify the volume location, where datas would be store if there if the container is restarted
      # mydevice-file_to_save
    # 5th: ports - expose containers port to the hors
    # 6th: network - configurate the network for container communication + setting the name of the network
    # 7th: restart - specify behavior if a container is stopped
    # Connect these containers themselves

    # Compose containers:
      # docker-compose -f old-docker-compose.yml up -d
    # Looking for containers errors: 
      # docker-compose -f docker-compose.yml logs -f

#------------------------------------#

# Defines all services (containers) for the application.
services:
  nginx:
    depends_on: # to start wordpress before nginx
      - wordpress
    build: requirements/nginx/.
    env_file: 
      - .env
      #secrets files to add?
    # volumes:
    #   - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: on-failure

  wordpress:
    depends_on: # to start mariadb before wordpress
      - mariadb
    build: requirements/wordpress/.
    env_file: 
      - .env
    # volumes:
		#   - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: on-failure

  mariadb:
    build: requirements/mariadb/.
    env_file: 
      - .env
    # volumes:
    #   - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

networks:
  inception:
  driver: bridge

  # volumes:
  #   wordpress:
  #     driver: local
  #     driver_opts:
  #     type: none
  #     o: bind
  #     device: ~/data/wordpress
  #   mariadb:
  #     driver: local
  #     driver_opts:
  #     type: none
  #     o: bind
  #     device: ~/data/mariadb
  