#-------------------------------------#
# Purpose:

  # Designed to simplify the use of multiple application like :
  # Nginx
  # Wordpress: website
  # MariaDB: for database

  # Service steps:
    # 1st: depends_on - check dependencies before building the container
    # 2nd: build - launch each service in separate containers
    # 3rd: environment (not hard-coded in the file) - setting environment variables of the container (API keys, passwords, database credentials securely)
    # 4th: volumes - specify the volume location, where datas would be store if there if the container is restarted
      # mydevice-file_to_save
    # 5th: ports - expose containers port to the hors
    # 6th: network - configurate the network for container communication + setting the name of the network
    # 7th: restart - specify behavior if a container is stopped
    # Connect these containers themselves

    # Compose containers:
      # docker-compose -f old-docker-compose.yml up -d
    # Looking for containers errors: 
      # docker-compose -f docker-compose.yml logs -f

#------------------------------------#

# Defines all services (containers) for the application.
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    ports:
      - "9000:9000"
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/mbriand/data/wordpress
      o: bind

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/mbriand/data/mysql
      o: bind

networks:
  inception:
    driver: bridge
